# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nginx # {{ .Values.image.repository }}
  tag: 1.7.9 # {{ .Values.image.tag }}


service:
  type: ClusterIP # {{ .Values.service.type }}
  port: 80 # {{ .Values.service.type }}


